import React, { useState, useEffect } from 'react';
import { HashRouter, Routes, Route } from 'react-router-dom';
import { StoreProvider } from './context/StoreContext';
import DashboardLayout from './components/dashboard/DashboardLayout';
import DashboardHome from './components/dashboard/DashboardHome';
import ProductManager from './components/dashboard/ProductManager';
import OrderManager from './components/dashboard/OrderManager';
import StoreCustomizer from './components/dashboard/StoreCustomizer';
import StorefrontLayout from './components/storefront/StorefrontLayout';
import StoreHome from './components/storefront/StoreHome';
import ProductDetails from './components/storefront/ProductDetails';